# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from airbot_proto.motion import arm_pb2 as airbot__proto_dot_motion_dot_arm__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in airbot_proto/motion/arm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FeedbackServiceStub(object):
    """/ For reference
    message RobotParams {
    string serial_number = 1;
    string hardware_version = 2;
    string base_firmware_version = 3;
    string end_firmware_version = 4;
    repeated string joint_names = 5;
    repeated airbot.motor.MotorParams joint_params = 6;
    repeated string sensor_names = 7;
    repeated airbot.sensor.SensorParams sensor_params = 8;
    }

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMode = channel.unary_unary(
                '/airbot_proto.motion.arm.FeedbackService/GetMode',
                request_serializer=airbot__proto_dot_motion_dot_arm__pb2.GetModeRequest.SerializeToString,
                response_deserializer=airbot__proto_dot_motion_dot_arm__pb2.GetModeResponse.FromString,
                _registered_method=True)
        self.GetParams = channel.unary_unary(
                '/airbot_proto.motion.arm.FeedbackService/GetParams',
                request_serializer=airbot__proto_dot_motion_dot_arm__pb2.GetParamsRequest.SerializeToString,
                response_deserializer=airbot__proto_dot_motion_dot_arm__pb2.GetParamsResponse.FromString,
                _registered_method=True)
        self.GetState = channel.unary_stream(
                '/airbot_proto.motion.arm.FeedbackService/GetState',
                request_serializer=airbot__proto_dot_motion_dot_arm__pb2.GetStateRequest.SerializeToString,
                response_deserializer=airbot__proto_dot_motion_dot_arm__pb2.GetStateResponse.FromString,
                _registered_method=True)


class FeedbackServiceServicer(object):
    """/ For reference
    message RobotParams {
    string serial_number = 1;
    string hardware_version = 2;
    string base_firmware_version = 3;
    string end_firmware_version = 4;
    repeated string joint_names = 5;
    repeated airbot.motor.MotorParams joint_params = 6;
    repeated string sensor_names = 7;
    repeated airbot.sensor.SensorParams sensor_params = 8;
    }

    """

    def GetMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetParams(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FeedbackServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMode,
                    request_deserializer=airbot__proto_dot_motion_dot_arm__pb2.GetModeRequest.FromString,
                    response_serializer=airbot__proto_dot_motion_dot_arm__pb2.GetModeResponse.SerializeToString,
            ),
            'GetParams': grpc.unary_unary_rpc_method_handler(
                    servicer.GetParams,
                    request_deserializer=airbot__proto_dot_motion_dot_arm__pb2.GetParamsRequest.FromString,
                    response_serializer=airbot__proto_dot_motion_dot_arm__pb2.GetParamsResponse.SerializeToString,
            ),
            'GetState': grpc.unary_stream_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=airbot__proto_dot_motion_dot_arm__pb2.GetStateRequest.FromString,
                    response_serializer=airbot__proto_dot_motion_dot_arm__pb2.GetStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'airbot_proto.motion.arm.FeedbackService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('airbot_proto.motion.arm.FeedbackService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FeedbackService(object):
    """/ For reference
    message RobotParams {
    string serial_number = 1;
    string hardware_version = 2;
    string base_firmware_version = 3;
    string end_firmware_version = 4;
    repeated string joint_names = 5;
    repeated airbot.motor.MotorParams joint_params = 6;
    repeated string sensor_names = 7;
    repeated airbot.sensor.SensorParams sensor_params = 8;
    }

    """

    @staticmethod
    def GetMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/airbot_proto.motion.arm.FeedbackService/GetMode',
            airbot__proto_dot_motion_dot_arm__pb2.GetModeRequest.SerializeToString,
            airbot__proto_dot_motion_dot_arm__pb2.GetModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/airbot_proto.motion.arm.FeedbackService/GetParams',
            airbot__proto_dot_motion_dot_arm__pb2.GetParamsRequest.SerializeToString,
            airbot__proto_dot_motion_dot_arm__pb2.GetParamsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/airbot_proto.motion.arm.FeedbackService/GetState',
            airbot__proto_dot_motion_dot_arm__pb2.GetStateRequest.SerializeToString,
            airbot__proto_dot_motion_dot_arm__pb2.GetStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ControlServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetMode = channel.unary_unary(
                '/airbot_proto.motion.arm.ControlService/SetMode',
                request_serializer=airbot__proto_dot_motion_dot_arm__pb2.SetModeRequest.SerializeToString,
                response_deserializer=airbot__proto_dot_motion_dot_arm__pb2.SetModeResponse.FromString,
                _registered_method=True)
        self.SetParams = channel.unary_unary(
                '/airbot_proto.motion.arm.ControlService/SetParams',
                request_serializer=airbot__proto_dot_motion_dot_arm__pb2.SetParamsRequest.SerializeToString,
                response_deserializer=airbot__proto_dot_motion_dot_arm__pb2.SetParamsResponse.FromString,
                _registered_method=True)
        self.SetState = channel.stream_stream(
                '/airbot_proto.motion.arm.ControlService/SetState',
                request_serializer=airbot__proto_dot_motion_dot_arm__pb2.SetStateRequest.SerializeToString,
                response_deserializer=airbot__proto_dot_motion_dot_arm__pb2.SetStateResponse.FromString,
                _registered_method=True)


class ControlServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetParams(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetState(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMode,
                    request_deserializer=airbot__proto_dot_motion_dot_arm__pb2.SetModeRequest.FromString,
                    response_serializer=airbot__proto_dot_motion_dot_arm__pb2.SetModeResponse.SerializeToString,
            ),
            'SetParams': grpc.unary_unary_rpc_method_handler(
                    servicer.SetParams,
                    request_deserializer=airbot__proto_dot_motion_dot_arm__pb2.SetParamsRequest.FromString,
                    response_serializer=airbot__proto_dot_motion_dot_arm__pb2.SetParamsResponse.SerializeToString,
            ),
            'SetState': grpc.stream_stream_rpc_method_handler(
                    servicer.SetState,
                    request_deserializer=airbot__proto_dot_motion_dot_arm__pb2.SetStateRequest.FromString,
                    response_serializer=airbot__proto_dot_motion_dot_arm__pb2.SetStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'airbot_proto.motion.arm.ControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('airbot_proto.motion.arm.ControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControlService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/airbot_proto.motion.arm.ControlService/SetMode',
            airbot__proto_dot_motion_dot_arm__pb2.SetModeRequest.SerializeToString,
            airbot__proto_dot_motion_dot_arm__pb2.SetModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/airbot_proto.motion.arm.ControlService/SetParams',
            airbot__proto_dot_motion_dot_arm__pb2.SetParamsRequest.SerializeToString,
            airbot__proto_dot_motion_dot_arm__pb2.SetParamsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetState(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/airbot_proto.motion.arm.ControlService/SetState',
            airbot__proto_dot_motion_dot_arm__pb2.SetStateRequest.SerializeToString,
            airbot__proto_dot_motion_dot_arm__pb2.SetStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
