# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from airbot_proto import utils_pb2 as airbot__proto_dot_utils__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in airbot_proto/utils_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UtilsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetState = channel.unary_unary(
                '/airbot_proto.utils.UtilsService/GetState',
                request_serializer=airbot__proto_dot_utils__pb2.GetStateRequest.SerializeToString,
                response_deserializer=airbot__proto_dot_utils__pb2.GetStateResponse.FromString,
                _registered_method=True)
        self.Startup = channel.unary_unary(
                '/airbot_proto.utils.UtilsService/Startup',
                request_serializer=airbot__proto_dot_utils__pb2.StartupRequest.SerializeToString,
                response_deserializer=airbot__proto_dot_utils__pb2.StartupResponse.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/airbot_proto.utils.UtilsService/Shutdown',
                request_serializer=airbot__proto_dot_utils__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=airbot__proto_dot_utils__pb2.ShutdownResponse.FromString,
                _registered_method=True)
        self.GetProductInfo = channel.unary_unary(
                '/airbot_proto.utils.UtilsService/GetProductInfo',
                request_serializer=airbot__proto_dot_utils__pb2.GetProductInfoRequest.SerializeToString,
                response_deserializer=airbot__proto_dot_utils__pb2.GetProductInfoResponse.FromString,
                _registered_method=True)
        self.LoadApp = channel.unary_unary(
                '/airbot_proto.utils.UtilsService/LoadApp',
                request_serializer=airbot__proto_dot_utils__pb2.LoadAppRequest.SerializeToString,
                response_deserializer=airbot__proto_dot_utils__pb2.LoadAppResponse.FromString,
                _registered_method=True)
        self.UnloadApp = channel.unary_unary(
                '/airbot_proto.utils.UtilsService/UnloadApp',
                request_serializer=airbot__proto_dot_utils__pb2.UnloadAppRequest.SerializeToString,
                response_deserializer=airbot__proto_dot_utils__pb2.UnloadAppResponse.FromString,
                _registered_method=True)


class UtilsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Startup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProductInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadApp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnloadApp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UtilsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=airbot__proto_dot_utils__pb2.GetStateRequest.FromString,
                    response_serializer=airbot__proto_dot_utils__pb2.GetStateResponse.SerializeToString,
            ),
            'Startup': grpc.unary_unary_rpc_method_handler(
                    servicer.Startup,
                    request_deserializer=airbot__proto_dot_utils__pb2.StartupRequest.FromString,
                    response_serializer=airbot__proto_dot_utils__pb2.StartupResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=airbot__proto_dot_utils__pb2.ShutdownRequest.FromString,
                    response_serializer=airbot__proto_dot_utils__pb2.ShutdownResponse.SerializeToString,
            ),
            'GetProductInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProductInfo,
                    request_deserializer=airbot__proto_dot_utils__pb2.GetProductInfoRequest.FromString,
                    response_serializer=airbot__proto_dot_utils__pb2.GetProductInfoResponse.SerializeToString,
            ),
            'LoadApp': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadApp,
                    request_deserializer=airbot__proto_dot_utils__pb2.LoadAppRequest.FromString,
                    response_serializer=airbot__proto_dot_utils__pb2.LoadAppResponse.SerializeToString,
            ),
            'UnloadApp': grpc.unary_unary_rpc_method_handler(
                    servicer.UnloadApp,
                    request_deserializer=airbot__proto_dot_utils__pb2.UnloadAppRequest.FromString,
                    response_serializer=airbot__proto_dot_utils__pb2.UnloadAppResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'airbot_proto.utils.UtilsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('airbot_proto.utils.UtilsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UtilsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/airbot_proto.utils.UtilsService/GetState',
            airbot__proto_dot_utils__pb2.GetStateRequest.SerializeToString,
            airbot__proto_dot_utils__pb2.GetStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Startup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/airbot_proto.utils.UtilsService/Startup',
            airbot__proto_dot_utils__pb2.StartupRequest.SerializeToString,
            airbot__proto_dot_utils__pb2.StartupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/airbot_proto.utils.UtilsService/Shutdown',
            airbot__proto_dot_utils__pb2.ShutdownRequest.SerializeToString,
            airbot__proto_dot_utils__pb2.ShutdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProductInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/airbot_proto.utils.UtilsService/GetProductInfo',
            airbot__proto_dot_utils__pb2.GetProductInfoRequest.SerializeToString,
            airbot__proto_dot_utils__pb2.GetProductInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadApp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/airbot_proto.utils.UtilsService/LoadApp',
            airbot__proto_dot_utils__pb2.LoadAppRequest.SerializeToString,
            airbot__proto_dot_utils__pb2.LoadAppResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnloadApp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/airbot_proto.utils.UtilsService/UnloadApp',
            airbot__proto_dot_utils__pb2.UnloadAppRequest.SerializeToString,
            airbot__proto_dot_utils__pb2.UnloadAppResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
